name: Deploy MkDocs

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv pip install --system mkdocs
        uv pip install --system "mkdocstrings[python]"
        uv pip install --system mkdocs-material
        uv pip install --system mkdocs-git-revision-date-localized-plugin
        uv pip install --system mkdocs-git-committers-plugin-2
        uv pip install --system mkdocs-git-authors-plugin
        uv pip install --system mkdocs-table-reader-plugin
        uv pip install --system mkdocs-jupyter

    - name: Build MkDocs
      run: mkdocs build

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        mkdocs gh-deploy --force
        
   
